before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
language: java
jdk:
- openjdk8
addons:
  chrome: stable
  firefox: latest
jobs:
  include:
#    - stage: tests
#      script:
#        - cd complete
#        - ./runtests.sh
#        - cd ..
    - stage: build-guide
      script: ./travis-build.sh
    - stage: republish-guides
env:
  global:
  - secure: YU9UMVRap7CmfqK1En1xcZ7TLVlVhO4Gs6bmheSzSCv8QYdMBpPL5fep6pmmtwsRqim+9246TGX0yhN8AlSEHORfPrcaW5l7Waz6QU2rWG8yjcdwIjxRH1aNE5VJIsP2QUIn0NVit1pArpywN4KncMANrYiM37ZcZ5+F9ffuPE2zN4AwQBVor/FM3xDv/7+2OLEMVUm90PfG0XhI6PDsHKvTcGhO807kzrakdEdkeT16eTw3gxxwARd/v6u0z3HhAGIU0efqBUZKGgMExcng1n7wXai+CKGdMHoDJabQJz+zEL7LMCtPosedVwSmqak7pZSsD7EzjqpNnfJs/IGUlZ+6XSHF4JS30UKDd/hlFcRKdwYVJqxvERR8pRmfm5FRTjPVKvaQ3g45T1KyTa1qF4Nl8ZYLGzXh181QsYgg/+haBiqw0jfhoNLuSpdC+M24JO5FRaKr93ptwAzNcKZxNrVX2ltJr3j+E2IeaFu0jaaZbjGaovJ7rctnK4UzFt63MsBzi1QwGzPr+3zmL82okrwFmZPo6HL8roz7+7dBP8oJYPOWaXEE/BFYz7FQtyJWHJl73YrSVIEiuXw/HPGNx9LAM7J2ecSw09EiicusIOTYMgBotudk1STIUDJd1lXna9u4LJ2Dc1fJ9YTKBB4pdYxG0CWR+t+k7Ygie+uAdD4=
  - secure: UJEQcBLAMYgW0aEd3ScPJb3wueLNQBhvnbaptvgY7ZgMp+biSaDzwABg16mxjzG3kLHUAi5xAXj7Ipanq3aglzkM4Kp+f4pB+4H+++5HO/Wz8Vi7NHSDjvwh7Zw1J2a2T82nS9Z1GKNYp6FTdNXMNE3s9AVI/HUky8XszXu2OpJLm7Ha8g/an2XQin8AFDTqmswGknx5l4j4exYzd0Niw6mrpGq3VGLBPWUduULw2zRGXO1KLqw9zmt7zfSDw9g2FW40GioK+t+Ndj55ORn4YIgmvKo6qP4u0MwWs4RiDVWocTLqxvlE9ddbBFRfW621WXLO8L0q4S3kWXs9Aul2iLUFpapkgzyS3OJVPmDGpLW04W4VocWttRaaE4Y/NO3lGRIs8qh4TUydUdgggLCOn9xZRWEk5ijCOw/v/y+Piw1KCrf5XZe3ONrPLyBPT51jAUWx8vz0QgKrelmOlzJzeqOjcsyMM1Xmeoc/84byg/zztZfYMr8ytasmIcEu/UehPDTDcROM/7aFsDBM4fvZ7CrrQmCgJQMQ4yQ+6PUE7x6/KYpg2RyABQbybuU9a/jGaro8PEOvmaELMS0rh/X88NariCL2fSA5Okxg1Hf6ZnOWLxK98CHgLcf/OaURG8C9pXuGK19ysRnyix3dqpzQca1paPcZEK1dHPVMUzG9HuE=
  - secure: gnyj5gnxAd5XMvvj2EzSKWFuC8sLOjKg2PR5+NZeE7ohjn53lfEvwDKVS9ufE3nuayRJL0KQ/VzOfW4oRYxp3LnHUzhHI47FNBkX1xcsIB47U0t7Zxd6enA9gcIIGR3/boC1AtJ/pc0PtEkYsd39qJgA0+7yXgORLWZN+SeXLTy1N/0DbUe85V8fMdmcJHWlsFuq2VL115dMs2rHuX0LV/TrruupzwG6MYPiQNmQpl9ym0kAd4jXP+oXML7EF/FuKZsVCOqmdh+0/GNhV/+TgkHFhtR6nkA6DsgmH0OiaSE57rrhNNdblcsqQRtk4wGWC4bEO501lrhzOTotN1ysH7k2H4bds30+ln1kqyaHNgYLeA+ZdMT9rwKsp1w3LmeUIOH9udN2qIGvggn7z5CXM3es41/+CUiHC+1tY/X2BUQ4ZpsjyuNczgWN74Eg3Km+tHEPwmVvXnHSdgKVFfqSbWTaeNhjb4CF2xoxDg/hkQDzlkO4yssWnnu2qtFnKroV2HQeyUuI//00vYE3NVPgz+jehiTU8Y1oRRP9A/zBMrNa211Z8YZZH0DC9jp/NPtMAgIcLIbQHCq49keFdCqJAVq0PsfVOFovQkBST33LF87Rf0vpLO+jpraLbyFwrrlyln5ul+t6lw5Ui/4HaxM7TMmQB4g9/2g3rYbT1iAfJp0=
